### ISSUE TITLE
Creative Commons

### ISSUE THREAD

**Issue by classiphil** [pavelzw/Analysis-I-Skript#60]
Dear pavelzw,

I am just starting to use Latex for my scripts and have a question concerning your latex documents. If I use parts of your latex code, may I still give a compiled document to other students? Or is there a copyright problem with Creative Commons? Some proofs are just very elegant, I think. :)

Best wishes
classiphil

**Comment by pavelzw** [comment]
For me, it's totally fine if you copy some LaTeX code into your documents from here. But you might want to consult [Dirk Hundertmark](https://www.math.kit.edu/iana1/~hundertmark) since he is the original author of most of this script and I only wrote them down in LaTeX while I was a student in his course.

His original hand-written notes can be found [here](https://www.math.kit.edu/iana1/lehre/ana12018w/).
